# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/refs/heads/main/themes/schema.json

version: 4
shell_integration: true
final_space: true
secondary_prompt:
  foreground: p:pacman_blue
  background: transparent
transient_prompt:
  template: "nu󰊠 "
  foreground: p:pacman_blue
  background: transparent
blocks:
  - type: prompt
    alignment: left
    segments:
      - template: " "
        foreground: white
        background: transparent
        type: text
        style: plain
      - template: "{{ .Path }}"
        foreground: blue
        background: transparent
        type: path
        style: plain
        options:
          style: full
      - foreground: p:grey
        background: transparent
        type: git
        style: plain
        options:
          branch_icon: " "
        templates:
          - " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <#a12036>{{ if gt .Behind 0 }}{{ end }}</><#10854e>{{if gt .Ahead 0 }}{{ end}}</>"
  - type: prompt
    alignment: right
    segments:
      - template: "  {{.Context}}{{if .Namespace}}:{{.Namespace}}{{end}}"
        foreground: p:kubernetes
        background: transparent
        type: kubectl
        style: plain
  - type: rprompt
    segments:
      - template: "{{ .Venv }} 󰌠 {{ .Full }}"
        foreground: "#FFFF00"
        background: transparent
        type: python
        style: plain
      - template: " {{ .Full }} "
        foreground: "#FFFF00"
        background: transparent
        type: go
        style: plain
      - template: "󱁢 {{.WorkspaceName}}"
        foreground: p:terraform
        background: transparent
        type: terraform
        style: plain
      - type: executiontime
        style: plain
  - type: prompt
    alignment: left
    segments:
      - template: "nu󰊠"
        background: transparent
        type: text
        style: plain
        foreground_templates:
          - "{{if .Env.POSH_VI_MODE}}p:google_yellow{{end}}"
          - "{{if gt .Code 0}}p:pacman_red{{end}}"
          - "{{if eq .Code 0}}p:pacman_blue{{end}}"
    newline: true
tooltips:
  - template:  {{.Project}}:{{.Region}}
    foreground: p:google_yellow
    background: transparent
    type: gcp
    style: plain
    tips:
      - gcloud
palette:
  google_yellow: "#ffce44"
  grey: "#6c6c6c"
  kubernetes: "#3a7be1"
  pacman_blue: "#46bfee"
  pacman_red: "#d03e19"
  terraform: "#623CE4"
