# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/heads/master/schema/config.json
gui:
  commandLogSize: 6
  theme:
    activeBorderColor:
      - "#d79921"
      - bold
    inactiveBorderColor:
      - "#7c6f64"
    searchingActiveBorderColor:
      - "#fabd2f"
      - bold
    optionsTextColor:
      - "#d79921"
    selectedLineBgColor:
      - "#3c3836"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d79921"
    cherryPickedCommitBgColor:
      - "#504945"
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
git:
  commit:
    signOff: true
