[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles Ôê£"
path = "~/dotfiles"

[[session]]
name = "arch"
path = "~/app/arch"

[[session]]
name = "blog"
path = "~/app/blog"
